In [2]:
import numpy as np 

In [3]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [4]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.arange(5, 200, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195]


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [12]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.49130231, 0.42554694, 0.60796893, 0.69246534, 0.0544883 ])

In [17]:
np.random.rand(5, 5)

array([[0.32754762, 0.2718217 , 0.44072151, 0.4370723 , 0.42588143],
       [0.09823864, 0.67260063, 0.24883996, 0.67710258, 0.23733967],
       [0.27437014, 0.58268042, 0.72394244, 0.81252928, 0.09081258],
       [0.03316759, 0.64309917, 0.53518299, 0.14352188, 0.5424337 ],
       [0.22369056, 0.70188476, 0.25330917, 0.08024383, 0.37540153]])

In [18]:
np.random.randn(5, 5)

array([[ 1.96298183,  1.26084019,  0.64428606,  0.31243653, -1.22237082],
       [ 0.29595665,  0.55821537,  0.52115116,  1.21182186, -0.19848637],
       [ 0.25607005,  1.72838342, -1.45227123,  0.41996304, -0.14391418],
       [ 0.90377614, -0.39726937,  0.64699616, -0.7057338 , -0.82626642],
       [-0.01611568,  1.81575905, -0.54226006, -0.99975838, -0.12118563]])

In [19]:
np.random.randint(1, 100, (5, 5))

array([[62, 12, 92, 34, 71],
       [43, 49, 32, 15, 52],
       [68, 92, 46, 95, 61],
       [50, 19, 60, 25, 47],
       [80,  1, 14, 28, 47]])

In [20]:
betko64 = np.random.randint(10, 100, 64)
betko64

array([61, 64, 27, 96, 23, 67, 80, 48, 64, 26, 63, 18, 77, 44, 63, 88, 63,
       30, 79, 92, 50, 94, 20, 35, 24, 77, 99, 15, 39, 89, 33, 56, 89, 21,
       43, 96, 78, 61, 31, 81, 27, 27, 10, 98, 95, 45, 94, 49, 66, 21, 64,
       98, 99, 18, 48, 91, 79, 27, 89, 64, 89, 68, 38, 30])

In [22]:
betko8x8 = betko64.reshape(8, 8)
betko8x8

array([[61, 64, 27, 96, 23, 67, 80, 48],
       [64, 26, 63, 18, 77, 44, 63, 88],
       [63, 30, 79, 92, 50, 94, 20, 35],
       [24, 77, 99, 15, 39, 89, 33, 56],
       [89, 21, 43, 96, 78, 61, 31, 81],
       [27, 27, 10, 98, 95, 45, 94, 49],
       [66, 21, 64, 98, 99, 18, 48, 91],
       [79, 27, 89, 64, 89, 68, 38, 30]])

In [29]:
daug_betko = np.random.randn(10000, 10000)
print(f'{daug_betko.argmin()} : {daug_betko.min()}, {daug_betko.argmax()}')

18970636 : -5.755728079562998, 81662970


In [32]:
print(daug_betko.shape)
daug_betko.dtype

(10000, 10000)


dtype('float64')

In [36]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[9 5 6 5 3 3 2 2 3 4]
9 5 [3 2 2 3]


In [37]:
print(betko10[::-1])

[4 3 2 2 3 3 5 6 5 9]


In [39]:
print(betko10[-3:])

[2 3 4]


In [41]:
betko8x8[:, :7]
print(betko8x8, betko8x8.shape, betko8x8[4, 4])

[[61 64 27 96 23 67 80 48]
 [64 26 63 18 77 44 63 88]
 [63 30 79 92 50 94 20 35]
 [24 77 99 15 39 89 33 56]
 [89 21 43 96 78 61 31 81]
 [27 27 10 98 95 45 94 49]
 [66 21 64 98 99 18 48 91]
 [79 27 89 64 89 68 38 30]] (8, 8) 78


In [42]:
print(betko8x8[2:5, 2:5])

[[79 92 50]
 [99 15 39]
 [43 96 78]]


In [43]:
betko8x8

array([[61, 64, 27, 96, 23, 67, 80, 48],
       [64, 26, 63, 18, 77, 44, 63, 88],
       [63, 30, 79, 92, 50, 94, 20, 35],
       [24, 77, 99, 15, 39, 89, 33, 56],
       [89, 21, 43, 96, 78, 61, 31, 81],
       [27, 27, 10, 98, 95, 45, 94, 49],
       [66, 21, 64, 98, 99, 18, 48, 91],
       [79, 27, 89, 64, 89, 68, 38, 30]])

In [45]:
virs_50 = betko8x8 >= 50
print(virs_50)

[[ True  True False  True False  True  True False]
 [ True False  True False  True False  True  True]
 [ True False  True  True  True  True False False]
 [False  True  True False False  True False  True]
 [ True False False  True  True  True False  True]
 [False False False  True  True False  True False]
 [ True False  True  True  True False False  True]
 [ True False  True  True  True  True False False]]


In [46]:
betko8x8[2:5, 2:5] = 77
print(betko8x8)

[[61 64 27 96 23 67 80 48]
 [64 26 63 18 77 44 63 88]
 [63 30 77 77 77 94 20 35]
 [24 77 77 77 77 89 33 56]
 [89 21 77 77 77 61 31 81]
 [27 27 10 98 95 45 94 49]
 [66 21 64 98 99 18 48 91]
 [79 27 89 64 89 68 38 30]]


In [47]:
betko8x8

array([[61, 64, 27, 96, 23, 67, 80, 48],
       [64, 26, 63, 18, 77, 44, 63, 88],
       [63, 30, 77, 77, 77, 94, 20, 35],
       [24, 77, 77, 77, 77, 89, 33, 56],
       [89, 21, 77, 77, 77, 61, 31, 81],
       [27, 27, 10, 98, 95, 45, 94, 49],
       [66, 21, 64, 98, 99, 18, 48, 91],
       [79, 27, 89, 64, 89, 68, 38, 30]])

In [48]:
septyni_septynetai = betko8x8[2:5, 2:5].copy()
septyni_septynetai

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [49]:
betko8x8[2:5, 2:5] = np.random.randint(10, 100, (3,3))
betko8x8

array([[61, 64, 27, 96, 23, 67, 80, 48],
       [64, 26, 63, 18, 77, 44, 63, 88],
       [63, 30, 37, 13, 20, 94, 20, 35],
       [24, 77, 77, 42, 78, 89, 33, 56],
       [89, 21, 68, 21, 15, 61, 31, 81],
       [27, 27, 10, 98, 95, 45, 94, 49],
       [66, 21, 64, 98, 99, 18, 48, 91],
       [79, 27, 89, 64, 89, 68, 38, 30]])

In [50]:
septyni_septynetai

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [51]:
simtukai = septyni_septynetai.copy() + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [52]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [53]:
simtukai + septyni_septynetai

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [54]:
simtukai / septyni_septynetai

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [56]:
betko8x8 ** np.random.randint(2, 10, (8, 8))

array([[       3721,           0, -1038305055,  -436207616,   148035889,
               4489, -1018167296,     5308416],
       [          0,       17576,        3969, -1864941312,      456533,
        -1333620736,    15752961,  1476395008],
       [  495628735,  -835117568,   324385413,    62748517,     3200000,
        -1951783040,     3200000, -1306177021],
       [  191102976, -1588183139,        5929,  1795711232,      474552,
          -71001063,  -331229983,     9834496],
       [-1234915375,         441,        4624,  1801088541,        3375,
          -19233191,         961,      531441],
       [   14348907,       19683,    10000000,  1079117888,    81450625,
         1894303437, -1619953600,   956385313],
       [  552235136,    85766121,        4096,    92111104,   919965907,
          790794752,           0,  -944569741],
       [ 1011793615,  2030534587,        7921,        4096,    62742241,
        -1841037312,     2085136,  -835117568]])